apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
  namespace: exam-krissmetryns
  labels:
    createdBy: "Nathan-Segers"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: api2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3d-k3s-default-agent-2 
      containers:
        - image: nathansegers/containers_23-24_december_api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 8080
          resources: {}

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
         
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30010
      environment:
      API_PORT: 80
      API_HOST: api